name: 'C++ Https Asycn Server Client'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libssl-dev libboost-all-dev googletest     

    - name: Build
      #run: cmake --build ${{github.workspace}}/server/build --config ${{env.BUILD_TYPE}}      
      run: cmake --build . --target all

    - name: Run tests
      working-directory: ${{github.workspace}}/server/test
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
